### ISSUE TITLE
Some ACPI Fixed and BAT0 

### ISSUE THREAD

**Issue by athlonreg** [liang0911/Thunderobot-G7000S-Hackintosh-By-Clover#1]
I tried to write some hotpatch, maybe can help you somewhere, can you delete all aml in your ACPI/patched and put these to try? 
[ACPI-Thunderobot-G7000S.zip](https://github.com/liang0911/Thunderobot-G7000S-Hackintosh-By-Clover/files/4157821/ACPI-Thunderobot-G7000S.zip)

**Comment by liang0911** [comment]
> I tried to write some hotpatch, maybe can help you somewhere, can you delete all aml in your ACPI/patched and put these to try?
> [ACPI-Thunderobot-G7000S.zip](https://github.com/liang0911/Thunderobot-G7000S-Hackintosh-By-Clover/files/4157821/ACPI-Thunderobot-G7000S.zip)

很感谢，有时间我会试一下。因为之前我也浪费了很多时间在修补ACPI上，但基本都没什么效果，后来就放弃了。
